---

- name: "ensure python3-pip is installed"
  apt:
    name: "python3-pip"
    state: present

- name: "ensure cloudsmith-cli python package is installed"
  pip:
    executable: pip3
    name: cloudsmith-cli

- name: "push package {{ package_filename }} to {{ repository }} for {{ os_identifier }}"
  shell: "cloudsmith push deb {{ repository }}/{{ os_identifier }} {{ package_filename }}"
  environment: "{{ env_vars }}"