---

- name: ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present

- name: add Nodesource apt key
  apt_key:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280"
    id: "68576280"
    state: present

- name: add NodeSource repositories for Node.js
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    state: present

- name: pin nodejs package to deb.nodesource.com origin (only for Ubuntu 18:04)
  template:
    src: nodejs_preference.j2
    dest: "{{ nodejs_preference_file }}"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution_release == "bionic"

- name: be sure nodejs is installed
  apt:
    name: nodejs
    state: present
    update_cache: true