---

- name: check for lxd unix socket
  set_fact:
    lxd_unix_socket: "{{ item }}"
  with_first_found:
    - "/var/lib/lxd/unix.socket"
    - "/var/snap/lxd/common/lxd/unix.socket"

- name: set container_name var
  set_fact:
    container_name: "{{ instance_name }}"

- name: "ensure container for {{ container_name }} is created and running"
  lxd_container:
    name: "{{ container_name }}"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: simplestreams
      alias: "{{ base_image }}"
    url: "unix:{{ lxd_unix_socket }}"
    wait_for_ipv4_addresses: true
    timeout: 600

- name: add container to inventory
  add_host:
    hostname: "{{ container_name }}"
    ansible_connection: lxd