---

- hosts: localhost
  gather_facts: true
  vars:
    instance_name: awx-debian-build
    base_image: "debian/buster/amd64"
  roles:
    - lxd-container

- hosts: "{{ hostvars.localhost.container_name }}"
  gather_facts: false
  roles:
    - python2

- hosts: "{{ hostvars.localhost.container_name }}"
  gather_facts: true
  vars:
    cloudsmith_api_key: "{{ lookup('env','CLOUDSMITH_API_KEY') }}"
    repository: "valet-sh/debian-stable"
    os_identifier: "debian/buster"
  roles:
    - build-awx-package

- hosts: localhost
  gather_facts: true
  vars:
    instance_name: awx-debian-build
    action: terminate
  roles:
    - lxd-container